English/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using English.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace English.Controllers
{
    [Authorize]
    public class CoursesController : Controller
    {
        private EnglishContext db = new EnglishContext();

        // GET: Courses
        public ActionResult Index()
        {
                string username = User.Identity.GetUserName();
            GameUser user = db.GameUsers.FirstOrDefault(u => u.UserName == username);
            return View(db.Courses.Where(course=>course.Owner==user.GameUserId).ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseId,CourseName,Visible,Cost,Paid")] Course course)
        {
            if (ModelState.IsValid)
            {
                string username = User.Identity.GetUserName();
                GameUser user = db.GameUsers.FirstOrDefault(u => u.UserName == username);
                
                string inn = Request.Form["IndexArray"];
                var aa = new JavaScriptSerializer().Deserialize<List<int>>(inn);

                course.Owner = user.GameUserId;

                course.Entries = new Collection<Entry>();
                foreach (var v in aa)
                {
                   
                    course.Entries.Add(db.Entries.Find(v));
                }
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(course);
        }


      



        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseId,CourseName,Visible,Cost")] Course course)
        {
            if (ModelState.IsValid)
            {

                db.Entry(course).State = EntityState.Modified;

                string inn = Request.Form["IndexArray"];
                var aa = new JavaScriptSerializer().Deserialize<List<int>>(inn);
                if (aa != null)
                {
                    course.Entries = new Collection<Entry>();
                    foreach (var v in aa)
                    {

                        course.Entries.Add(db.Entries.Find(v));
                    }

                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
      
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [ActionName("Join")]
        [Authorize]
        public ActionResult JoinToCourse(int id)
        {
            string username = User.Identity.GetUserName();
            GameUser user = db.GameUsers.FirstOrDefault(u => u.UserName == username);
            if (user.Courses == null)
            {
                user.Courses = new Collection<Course>();
            }
            var course = db.Courses.Find(id);
            if (course != null)
            {
                if (course.Paid && user.PremiumPoints >= course.Cost || !course.Paid)
                {
                    user.Courses.Add(course);
                    user.PremiumPoints -= course.Cost.GetValueOrDefault(0);
                    if(user.UserWords==null)
                    {
                        user.UserWords = new List<UserWords>();
                    }
                    var WordsList = course.Entries;
                    foreach(var word in WordsList)
                    {
                        user.UserWords.Add(new UserWords() { Strike = 0, IsTimeToLearn=true, LastUsage = DateTime.Now, entry = word,Course=course });
                    }
                }
            }
            db.Entry(user).State=EntityState.Modified;
            db.SaveChanges();
            return View("Index",db.Courses.ToList());  
        }

        public JsonResult AutoCompleteWord(string term)
        {
            db.Configuration.LazyLoadingEnabled = false;
            db.Configuration.ProxyCreationEnabled = false;
            var result = db.Entries.Where(r => r.EnglishWord.StartsWith(term)).ToList();
            
            return Json(result,JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Browse()
        {
            return View(db.Courses.Where(course=> course.Visible).ToList());
        }
    }
}

English/Controllers/LearnController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using English.ViewModels;
using English.Models;
using Microsoft.AspNet.Identity;
using System.Collections;
namespace English.Controllers
{
    public class LearnController : Controller
    {
        private EnglishContext db = new EnglishContext();
        // GET: Learn
        public ActionResult Index(int id)
        {
            var wordForUser = new WordForUser();
            string name = User.Identity.GetUserName();
            wordForUser.GameUser = db.GameUsers.First(a => a.UserName == name);
            var wordsToUpdate = db.UsersWords.Where(collection => collection.Course.CourseId == id && collection.GameUsers.Count(u => u.GameUserId == wordForUser.GameUser.GameUserId) > 0);

            foreach (var entry in wordsToUpdate.ToList())
            {
                entry.Update();
                db.Entry(entry).State = EntityState.Modified;
            }
            db.SaveChanges();
            wordForUser.WordCollection =
            db.UsersWords.Where(collection => collection.Course.CourseId == id && collection.IsTimeToLearn).Select(c => c.entry).ToList();

            if (wordForUser.WordCollection.Count == 0)
            {
                return RedirectToAction("Browse", "Courses");
            }
            ViewBag.CourseId = id;
            return View(wordForUser);
        }

        public ActionResult AddPoints(int Points)
        {
            String username = User.Identity.GetUserName();
            GameUser user = db.GameUsers.FirstOrDefault(u => u.UserName == username);
            user.Points += Points;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return Content("OK");
        }

        public JsonResult CheckWord(int Id, string Answer, int Points,int CourseId)
        {
            String username = User.Identity.GetUserName();
            var result = new Hashtable();
            GameUser user = db.GameUsers.FirstOrDefault(u => u.UserName == username);
            var Usage = db.UsersWords.Where(usage => usage.entry.EntryId == Id && usage.Course.CourseId==CourseId).FirstOrDefault();
            if (Usage.ContainWord(Answer))
            {
                user.Points += Points;
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                Usage.LearnResult(true);
                result.Add("result", "yes");
            }
            else
            {
                Usage.LearnResult(false);
                result.Add("result", "no");
            }
            result.Add("alternatives", Usage.GetAlternatives());
            Usage.Update();
            db.Entry(Usage).State = EntityState.Modified;
            db.SaveChanges();
            db.Configuration.LazyLoadingEnabled = false;
            db.Configuration.ProxyCreationEnabled = false;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult GetSandwitches(int Id)
        {
            var entry = db.UsersWords.Where(collection => collection.Course.CourseId == Id && collection.IsTimeToLearn).Select(c => c.entry).OrderBy(a => System.Guid.NewGuid()).FirstOrDefault();
            return PartialView("_Restaurant", entry);
        }
    }
}

English/Views/Courses/Browse.cshtml
@using English.Models
@using Microsoft.AspNet.Identity
@model IEnumerable<English.Models.Course>

@{
    ViewBag.Title = "Browse";
    var name = User.Identity.GetUserName();
    var user = new EnglishContext().GameUsers.FirstOrDefault(u => u.UserName == name);
}

<h2>Browse</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>
        <th>
            @Html.DisplayName("Action")
        </th>
   
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @{
                    if(user!=null && user.Courses.Count(c => c.CourseId == item.CourseId) == 0 && ((item.Paid && user.PremiumPoints>=item.Cost) || !item.Paid))
                    {
                        @Ajax.ActionLink("Join", "Join", new {id = item.CourseId}, new AjaxOptions {OnComplete = "Join(this);"}, new {@class = "btn btn-default", id = "Join" + item.CourseId})
                    }
                    else if (user != null && user.Courses.Count(c => c.CourseId == item.CourseId) == 0 && item.Paid && user.PremiumPoints < item.Cost)
                    {
                        @Ajax.ActionLink("Join", "Join", new { id = item.CourseId }, new AjaxOptions { OnComplete = "Join(this);" }, new { @class = "btn btn-warning disabled", id = "Join" + item.CourseId })
                    }
                    else if (user != null && user.UserWords.Count(u=>u.IsTimeToLearn && u.Course.CourseId==item.CourseId)==0)
                    {
                        
                        @Html.ActionLink("Done", "Index", "Learn", new { id = item.CourseId }, new { @class = "btn btn-success" })
                    }
                    else if (user != null )
                    {

                        @Html.ActionLink("Learn", "Index", "Learn", new { id = item.CourseId }, new { @class = "btn btn-default" })
                    }
}
            </td>
     
        </tr>
    }

</table>
@section Scripts
{
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        function Join(e) {
            $(e).removeClass("btn-default");
            $(e).addClass("btn-success");
            $(e).addClass("disabled");
            alert("Joined!");
            location.reload();
        }
    </script>
}

English/Views/Courses/Create.cshtml
@using English.Models
@using Microsoft.AspNet.Identity
@model English.Models.Course

@{
    ViewBag.Title = "Create";
     var name = User.Identity.GetUserName();
    var user = new EnglishContext().GameUsers.FirstOrDefault(u => u.UserName == name);
}



<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.Hidden("IndexArray")

    <div id="tabs">
        <ul>
            <li><a href="#fragment-1">Main Settings</a></li>
            <li><a href="#fragment-2">Words</a></li>
        </ul>
        <div id="fragment-1">
        
        
            <div class="form-horizontal">
                <h4>Main Settings</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Visible, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Visible)
                            @Html.ValidationMessageFor(model => model.Visible, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                
                
                <div class="form-group">
                    @Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Paid)
                            @Html.ValidationMessageFor(model => model.Paid, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                
                
                <div class="form-group" id="CostDiv" style="display:none;">
                    @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Cost)
                            @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                

            
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })

                    </div>
                </div>
            </div>
        
        
        
        
        
        
        
        </div>
        <div id="fragment-2">
       
            <div class="form-horizontal">
                <h4>Words in Course</h4>
                <hr />
                <div class="form-group">
                  
                    <div class="col-md-10">
                        @Html.TextBox("Country", "", new { @class = "form-control" })
                        <input type="button" id="AddWord" class="btn btn-default" value="Add"/>

                       
                        <div class="wrap">

                        </div>
                    </div>
                    
                </div>
            </div>

        
        
        </div>
     
    </div>






   
}











@section Scripts
{
    @Styles.Render("~/Content/themes/base/autocomplete.css")
@Styles.Render("~/Content/themes/base/wrap.css")
    @Scripts.Render("~/bundles/jqueryval")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"> </script>
    <script src="~/Scripts/jquery-ui-1.11.4.js"> </script>
    <script type="text/javascript">
        var i = 0;
        var allData = [];
        var wordsId = [];
        var stringWords = [];


        $(document).ready(function() {


            $("#AddWord").click(function() {
                for (var j = 0; j < allData.length; j++) {
                    if (allData[j].EnglishWord === $('#Country').val() && wordsId.indexOf(allData[j].EntryId) === -1) {
                        wordsId.push(allData[j].EntryId);
                        stringWords.push(allData[j].EnglishWord);
                        var newEntry = $(" " +
                            "" +
                            "  <div class='box'> <span id='remove" + i + "' class='close-btn'><a href='#'>X</a></span> <div class='boxInner'>  <p> " + $('#Country').val() + " </p>   </div> <input type='hidden' class='buut' readonly name='usage" + i + "' value='" + $('#Country').val() + "'/></div>");
                        $(".wrap").append(newEntry);
                        newEntry.hide().fadeIn(500);
                        var ss = JSON.stringify(wordsId);
                        $("#IndexArray").val(ss);
                        i = i + 1;
                    }
                }

            });


            $(".wrap").on("click", ".close-btn", function() {
                $(this).parent().fadeOut(250, function() {
                    var word = $(this).parent().find(".buut").val();
                    for (var jNumber = 0; jNumber < stringWords.length; jNumber++) {

                        if (stringWords[jNumber] === word) {
                            wordsId.splice(jNumber, 1);
                            stringWords.splice(jNumber, 1);
                        }
                    }
                    var ss = JSON.stringify(wordsId);
                    $("#IndexArray").val(ss);
                    $(this).remove();
                });

            });

            $("#tabs").tabs({
                show: { effect: "fadeIn", duration: 800 }
            });

            $("#Paid").change(function() {
                var check = $(this).prop('checked');
                if (check) {
                    $("#CostDiv").fadeIn();
                } else {
                    $("#CostDiv").fadeOut();
                }
            });
            $("#Country").autocomplete({
                source: function(request, response) {
                    $.ajax({
                        url: "/Courses/AutoCompleteWord",
                        type: "POST",
                        dataType: "json",
                        data: { term: request.term },
                        success: function(data) {
                            allData = data;
                            response($.map(data, function(item) {
                                return { value: item.EnglishWord };
                            }));

                        }
                    });
                },
                messages: {
                    noResults: "",
                    results: ""
                }
            });
        });

    </script>
}

English/Views/Courses/Delete.cshtml
@model English.Models.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visible)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visible)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

English/Views/Courses/Details.cshtml
@model English.Models.Course

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visible)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visible)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CourseId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

English/Views/Courses/Edit.cshtml
@model English.Models.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Hidden("IndexArray")


    <div id="tabs">
        <ul>
            <li><a href="#fragment-1">Main Settings</a></li>
            <li><a href="#fragment-2">Words</a></li>
        </ul>
        <div id="fragment-1">


            <div class="form-horizontal">
                <h4>Main Settings</h4>
                <hr />
                @Html.HiddenFor(model=>model.CourseId)
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Visible, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Visible)
                            @Html.ValidationMessageFor(model => model.Visible, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Paid)
                            @Html.ValidationMessageFor(model => model.Paid, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <div class="form-group" id="CostDiv" style="display:none;">
                    @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Cost)
                            @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>




                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Update" class="btn btn-default" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })

                    </div>
                </div>
            </div>







        </div>
        <div id="fragment-2">

            <div class="form-horizontal">
                <h4>Words in Course</h4>
                <hr />
                <div class="form-group">

                    <div class="col-md-10">
                        @Html.TextBox("Country", "", new { @class = "form-control" })
                        <input type="button" id="AddWord" class="btn btn-default" value="Add" />


                        <div class="wrap">

                        </div>
                    </div>

                </div>
            </div>




        </div>

    </div>







}


@section Scripts
{
    @Styles.Render("~/Content/themes/base/autocomplete.css")
@Styles.Render("~/Content/themes/base/wrap.css")
    @Scripts.Render("~/bundles/jqueryval")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"> </script>
    <script src="~/Scripts/jquery-ui-1.11.4.js"> </script>
    <script type="text/javascript">
        var i = 0;
        var allData = [];
        var wordsId = [];
        var stringWords = [];
        @{

            foreach (var a in Model.Entries)
            {
<text>
        wordsId.push(@a.EntryId);
        stringWords.push('@a.EnglishWord');
</text>
            }
            
        }


        function Load() {
            for (var j = 0; j < wordsId.length; j++) {
                var newEntry = $("<div class='box'> <span id='remove" + j + "' class='close-btn'><a href='#'>X</a></span> <div class='boxInner'>  <p> " + stringWords[j] + " </p>   </div> <input type='hidden' class='buut' readonly name='usage" + j + "' value='" + stringWords[j] + "'/></div>");
                $(".wrap").append(newEntry);
                newEntry.hide().fadeIn(500);
                i = j;
            }
        }

        $(document).ready(function () {
            Load();
   

            $("#AddWord").click(function () {
                for (var j = 0; j < allData.length; j++) {
                    if (allData[j].EnglishWord === $('#Country').val() && wordsId.indexOf(allData[j].EntryId) === -1) {
                        wordsId.push(allData[j].EntryId);
                        stringWords.push(allData[j].EnglishWord);
                        var newEntry = $("<div class='box'> <span id='remove" + i + "' class='close-btn'><a href='#'>X</a></span> <div class='boxInner'>  <p> " + $('#Country').val() + " </p>   </div> <input type='hidden' class='buut' readonly name='usage" + i + "' value='" + $('#Country').val() + "'/></div>");
                        $(".wrap").append(newEntry);
                        newEntry.hide().fadeIn(500);
                        var ss = JSON.stringify(wordsId);
                        $("#IndexArray").val(ss);
                        i = i + 1;
                    }
                }

            });


            $(".wrap").on("click", ".close-btn", function () {
                $(this).parent().fadeOut(250, function () {
                    var word = $(this).parent().find(".buut").val();
                    for (var jNumber = 0; jNumber < stringWords.length; jNumber++) {

                        if (stringWords[jNumber] === word) {
                            wordsId.splice(jNumber, 1);
                            stringWords.splice(jNumber, 1);
                        }
                    }
                    var ss = JSON.stringify(wordsId);
                    $("#IndexArray").val(ss);
                    $(this).remove();
                });

            });


            $("#tabs").tabs({
                show: { effect: "fadeIn", duration: 800 }
            });

            $("#Paid").change(function () {
                var check = $(this).prop('checked');
                if (check) {
                    // $("#CostDiv").css("visibility", "");
                    $("#CostDiv").fadeIn();
                } else {
                    //  $("#CostDiv").css("visibility", "hidden");
                    $("#CostDiv").fadeOut();
                }
            });
            $("#Country").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Courses/AutoCompleteWord",
                        type: "POST",
                        dataType: "json",
                        data: { term: request.term },
                        success: function (data) {
                            allData = data;
                            response($.map(data, function (item) {
                                return { value: item.EnglishWord };
                            }))

                        }
                    })
                },
                messages: {
                    noResults: "",
                    results: ""
                }
            });
        })

    </script>
}

English/Views/Courses/Index.cshtml
@using English.Models
@using Microsoft.AspNet.Identity
@model IEnumerable<English.Models.Course>

@{
    ViewBag.Title = "My Courses";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Visible)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Visible)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CourseId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CourseId })
            </td>
        </tr>
    }
</table>

@section Scripts
{
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/bundles/jqueryval")
}